### ISSUE TITLE
Recognizing more media types

### ISSUE THREAD

**Issue by acarl005** [athityakumar/colorls#178]
### Description

Thanks for opening this issue. Add a brief description of what this issue is, and how to recreate it. Do tag the relevant issue(s) and PR(s) below. If required, add some screenshot(s) to showcase the issue.

- Relevant Issues : (none)
- Relevant PRs : (none)
- Type of issue :
  - [ ] Installation
  - [ ] Font-related
  - [x] Feature request
  - [ ] Bug in existing feature
  - [ ] Developer mode : Code quality / Tests / Documentation

I propose adding the following to `file-aliases.yaml`:

```yaml
webp:             "image"
tiff:             "image"
pxm:              "image"
m4a:              "audio"
wav:              "audio"
flac:             "audio"
mov:              "video"
flv:              "video"
```

These are some relatively common media types I encounter at work and I thought they ought to have the right glyphs.
