### ISSUE TITLE
Dracula theme for colorls

### ISSUE THREAD

**Issue by mamyn0va** [athityakumar/colorls#364]
Hello there,

Thanks for the great job, it makes the developer journey much more valuable !

I wanted to post my personal colorls config that is inspired by the [Dracula color palette](https://draculatheme.com/contribute/#color-palette). These are not the exact same colors as colorls only have a limited colors set, but it's almost that.

Here is the my ~/.config/colorls/dark_colors.yaml:

```config
 Main Colors
unrecognized_file: slateblue
recognized_file:   snow
dir:               magenta

# Link
dead_link: red
link:      cyan

# Access Modes
write:     cyan
read:      magenta
exec:      aqua
no_access: indianred

# Age
hour_old:    snow
day_old:     lightgray
no_modifier: dimgray

# File Size
file_large:  snow
file_medium: lightgray
file_small:  dimgray

# Random
report: white
user:   cyan
tree:   cyan
empty:  aqua
error:  red
normal: aqua

# Git
addition:     chartreuse
modification: darkkhaki
deletion:     darkred
untracked:    darkorange
unchanged:    forestgreen
```

Here is a screenshot:

![Screen Capture_select-area_20200528124146](https://user-images.githubusercontent.com/11281228/83132233-5f966900-a0e1-11ea-858e-90415407b6c1.png)

If you know a cleaner way to achieve the same goal, I would be happy to contribute!

Thx

**Comment by avdv** [comment]
Thank you for this, that looks quite nice!

Seems it's not possible to use RGB values, only color names... I'll try to come up with a fix.

**Comment by bigpick** [comment]
Per https://github.com/athityakumar/colorls/issues/165 I think you should be able to get away with specifying the ANSI colors and it should pick them up instead. For example, for the ones if ANSI values defined already by Dracula:

```yaml
# Main Colors
unrecognized_file: red
recognized_file:   white
dir:               blue

# Link
dead_link: red
link:      cyan

# Access Modes
write:     magenta
read:      blue
exec:      cyan
no_access: red

# Age
hour_old:    white
day_old:     lightgray
no_modifier: dimgray

# File Size
file_large:  white
file_medium: lightgray
file_small:  dimgray

# Random
report: white
user:   magenta
tree:   cyan
empty:  cyan
error:  red
normal: cyan

# Git
addition:     chartreuse
modification: darkkhaki
deletion:     darkred
untracked:    darkorange
unchanged:    forestgreen
```

And it should be using the magenta/cyan/etc defined by Dracula
